### ISSUE TITLE
setup openerp zimbra connector

### ISSUE THREAD

**Issue by zxcoolman** [vnc-biz/openerp-zimbra-connector#1]
Hi everybody

I use openerp version 7.
I installed vnc_zimbra_connector with successful.
![zimbra_openerp_server_installed](https://f.cloud.github.com/assets/3357331/974474/09b6bd5a-0656-11e3-9d4f-b308af4d0575.png)

I installed zcs-openerp-connector too :

zimbra@mail:/root$ zmpkg list
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version                Description
+++-========================-======================-========================================================
ii  zcs-core-libs            8.0.2-0.3-ironmaiden-2 Makes ZCS core libraries available in the jsp containers
ii  zcs-lib-gson             1.7.2.2-ironmaiden-0   Google json library
ii  zcs-lib-gson22           2.2.2.2-ironmaiden-1   Google json library
ii  zcs-lib-javacsv          2.0.0.2-ironmaiden-0   Java CSV library
ii  zcs-lib-json-simple      1.1.1.6-ironmaiden-0   Simple JSON library
ii  zcs-lib-redstone-xmlrpc  1.1.1.4-ironmaiden-0   Redstone XML-RPC library
ii  zcs-lib-vnc-common       0.12.2-ironmaiden-2    Common classes library for VNC packages
ii  zcs-openerp-connector    1.2.5.0-ironmaiden-0   OpenERP integration
ii  zcs-zmpkg                1.3.0.12-ironmaiden-0  Zimbra package management system

but the connection with connector don't work
![error_zimbra_connector](https://f.cloud.github.com/assets/3357331/974512/891e067e-0657-11e3-9729-fc446b8aee6e.png)

I give you the log error in file 

INFO [OpenERPConnector] Calling XMLRPC service: https://erp7.xxxx.net:8069/xmlrpc/db
ERROR [OpenERPConnector] getDatabase call failed redstone.xmlrpc.XmlRpcException: A network error occurred.
redstone.xmlrpc.XmlRpcException: A network error occurred.
        at redstone.xmlrpc.XmlRpcClient.endCall(XmlRpcClient.java:334)
        at redstone.xmlrpc.XmlRpcClient.invoke(XmlRpcClient.java:190)
        at biz.vnc.zimbra.openerp_zimlet.Connector.getDatabase(Connector.java:96)
        at org.apache.jsp.com_005fzimbra_005ferp_005fmail_005fconnector.GetDatabaseRpc_jsp._jspService(org.apache.jsp.com_005fzimbra_005ferp_005fmail_005fconnector.GetDatabaseR
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:403)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:476)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:366)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:574)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:293)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:120)
        at com.zimbra.cs.zimlet.ZimletResources.service(ZimletResources.java:98)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:52)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at com.zimbra.cs.zimlet.ZimletFilter.doFilter(ZimletFilter.java:240)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:57)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:268)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:45)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:114)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:344)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:315)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:556)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:317)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:81)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.UnknownHostException: erp7.xxxx.net
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
        at java.net.Socket.connect(Socket.java:579)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
 at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
        at com.zimbra.common.net.CustomSSLSocket.connect(CustomSSLSocket.java:309)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:378)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:473)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:270)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:327)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:931)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1090)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at redstone.xmlrpc.XmlRpcClient.endCall(XmlRpcClient.java:326)
        ... 71 more
Total time for which application threads were stopped: 0.0003390 seconds

Thanks and kind regards,
zxcoolman

**Comment by dhaval-vnc** [comment]
Please check that you're able to connect to openERP host on 8069 port from your zimbra host.

**Comment by stefansaenger** [comment]
the URL you are using seems to be wrong; port 8069 indicates that you are connecting directly to openerps HTTP service, and hence https is wrong. Try using only http here...

**Comment by zxcoolman** [comment]
Thanks you very much with ip address it's work !!! I'm apologize

Escuse me but until one day i have tried on openerp version 6 without successful.
the plugin installation crash with error python (screen windows if you want ;) ) .

Do you know if plugin work with version 6 of openerp ?

Thanks,
zxcoolman

**Comment by dhaval-vnc** [comment]
@zxcoolman  We tried with version 6.1.x and 7.x only.
